/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myconnector.mainframe;

/**
 *
 * @author serieznyi
 */
public class GlobalPanel extends javax.swing.JPanel {

    /**
     * Creates new form GlobalPanel
     */
    public GlobalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel1 = new myconnector.mainframe.StartPanel();
        clientMainPanel1 = new myconnector.client.gui.ClientMainPanel();
        serverMainPanel1 = new myconnector.server.gui.ServerMainPanel();

        setLayout(new java.awt.CardLayout());
        add(startPanel1, "card2");
        add(clientMainPanel1, "card4");
        add(serverMainPanel1, "card5");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myconnector.client.gui.ClientMainPanel clientMainPanel1;
    private myconnector.server.gui.ServerMainPanel serverMainPanel1;
    private myconnector.mainframe.StartPanel startPanel1;
    // End of variables declaration//GEN-END:variables
}
