/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myconnector.mainframe;

import java.awt.CardLayout;
import java.io.IOException;
import java.net.UnknownHostException;
import javax.swing.JTextArea;
import myconnector.MyConnector;
import myconnector.client.Client;
import myconnector.network.Network;
import myconnector.server.Server;

/**
 *
 * @author serieznyi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame1
     */
    private Server server;
    private Client client;
    private String mode;

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
        this.getGlobalPanel().getStartPanel().setMode(mode);
    }
   
    public MainFrame() throws IOException {
        initComponents();
        
        MyConnector.main = this;
        
        this.setLocation(400, 150);
        
        this.server = new Server();
    }
    
    public void startClient(String ip) throws UnknownHostException, IOException
    {
        this.client = new Client(ip);
        this.client.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel1 = new myconnector.mainframe.ViewPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(viewPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_item_exitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myconnector.mainframe.ViewPanel viewPanel1;
    // End of variables declaration//GEN-END:variables
    
    public void showPanel(String name) {
        CardLayout cl = (CardLayout)(this.getGlobalPanel().getLayout());
        cl.show(this.getGlobalPanel(), name);
    }
    
    public ViewPanel getGlobalPanel() {
        return viewPanel1;
    }
    
    public Network getNetwork() 
    {
        return (Network)(mode.equals("Server") ? this.server : this.client);
    }
    
    public Server getServer() {
        return server;
    }

    public Client getClient() {
        return client;
    }

    public JTextArea getLogTextArea() {
        return this.viewPanel1.getWorkingPanel().getLogTextArea();
    }
}
