/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myconnector.mainframe;

import java.awt.CardLayout;
import java.awt.Rectangle;
import java.awt.Window;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import myconnector.MyConnector;
import myconnector.client.Client;
import myconnector.client.ViewFrame;
import myconnector.network.Network;
import myconnector.server.Server;

/**
 *
 * @author serieznyi
 */
public class MainFrame extends javax.swing.JFrame {
    
    private Server server;
    private Client client;
    private String mode;

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }
    
    public void startClient(String ip) throws UnknownHostException, IOException
    {
        this.client = new Client(ip);
    }
    
    public void showPanel(String name) {
        CardLayout cl = (CardLayout)(this.mainPanel2.getLayout());
        cl.show(this.mainPanel2, name);
    }
    
    public JTextArea getLogTextArea() {
        return this.getWorkingPanel().getLogTextArea();
    }
    
    public Network getNetwork() 
    {
        return (Network)(mode.equals("Server") ? this.server : this.client);
    }
    
    /**
     * Creates new form MainFrame2
     */
    public MainFrame() {
        try {
            initComponents();
            
            MyConnector.view = new ViewFrame();
            
            MyConnector.main = this;
            
            this.setLocation(400, 150);
            this.setResizable(false);
            
           // MyConnector.main.setType(Type.POPUP);
          //  MyConnector.main.setUndecorated(true);
            
            this.server = new Server();
            
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel2 = new myconnector.mainframe.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel2, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private myconnector.mainframe.MainPanel mainPanel2;
    // End of variables declaration//GEN-END:variables

    public WorkingPanel getWorkingPanel() {
        return this.mainPanel2.getWorkingPanel();
    }
    
    public void fixedFrame()
    {
        Rectangle view_frame_rect = myconnector.MyConnector.view.getBounds();
        System.out.println("Start fixed");
        System.out.println(view_frame_rect);
        
        double main_w = ((int)view_frame_rect.width * 0.2);
        double main_h = ((int)view_frame_rect.height * 0.5);
        
        double main_x = view_frame_rect.x + view_frame_rect.width - main_w;
        double main_y = view_frame_rect.y + view_frame_rect.height - main_h;
        
       // main_x = main_x - view_frame_rect.x;
       // main_y = main_y - view_frame_rect.y;
        
        Rectangle new_pos_main;
        new_pos_main = new Rectangle((int)main_x, (int)main_y, (int)main_w, (int)main_h);
        
        myconnector.MyConnector.main.setBounds(new_pos_main);
        
        System.out.println(new_pos_main);
    }
    
}
